// Executable autogenerated by the Boron compiler
// Version 0.25.1
// Created on 2022/07/24 at 13:00:59 local time

#include <stdio.h>
#include <stdbool.h>


// Structs begin here

// Functions begin here
int main() {
int x = 3;
}